language: php

php:
  - nightly

jobs:
  include:
    install:
    - travis_retry composer install --no-interaction --no-suggest
    before_script:
    - composer self-update
    - composer install --no-interaction
    - stage: config
      php: nightly
      script:
        - touch database/database.sqlite
        - cp .env.travis .env
        - php artisan key:generate
        - php artisan migrate
    - stage: code sniffer
      php: nightly
      script:
        - ./vendor/bin/phpcs --standard=PSR2 app/Events --colors
        - ./vendor/bin/phpcs --standard=PSR2 app/Http/Controllers/API --colors
        - ./vendor/bin/phpcs --standard=PSR2 app/Http/Requests --colors
        - ./vendor/bin/phpcs --standard=PSR2 app/Jobs --colors
        - ./vendor/bin/phpcs --standard=PSR2 app/Listeners --colors
        - ./vendor/bin/phpcs --standard=PSR2 app/Observers --colors
        - ./vendor/bin/phpcs --standard=PSR2 app/Models --colors
        - ./vendor/bin/phpcs --standard=PSR2 database/seeds --colors
    - stage: unit tests
      php:
      - nightly
      script:
        - ./vendor/bin/phpunit

after_success:
  - travis_retry php coveralls.phar -v
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.cache/composer
